"""add default workflow id to template

Revision ID: a64d7efb1234
Revises: 960bd0ac395b
Create Date: 2024-03-31 11:05:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a64d7efb1234'
down_revision = '960bd0ac395b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('default_workflow_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_templates_default_workflow_id_workflows', 'templates', 'workflows', ['default_workflow_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_templates_default_workflow_id_workflows', 'templates', type_='foreignkey')
    op.drop_column('templates', 'default_workflow_id')
    # ### end Alembic commands ### 