"""add email field to user model

Revision ID: b1ae7fb5242a
Revises: 6c6f2e7a1122
Create Date: 2024-03-28 22:03:55.979351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1ae7fb5242a'
down_revision = '6c6f2e7a1122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    # ### end Alembic commands ### 