"""add email field to user model

Revision ID: 1085f8bfa2c4
Revises: 6c6f2e7a1122
Create Date: 2025-03-19 11:37:59.339267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1085f8bfa2c4'
down_revision: Union[str, None] = '6c6f2e7a1122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('casbin_rule')
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    op.create_table('casbin_rule',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ptype', sa.VARCHAR(length=255), nullable=True),
    sa.Column('v0', sa.VARCHAR(length=255), nullable=True),
    sa.Column('v1', sa.VARCHAR(length=255), nullable=True),
    sa.Column('v2', sa.VARCHAR(length=255), nullable=True),
    sa.Column('v3', sa.VARCHAR(length=255), nullable=True),
    sa.Column('v4', sa.VARCHAR(length=255), nullable=True),
    sa.Column('v5', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
