"""add field_value model

Revision ID: 5cd18eb7121b
Revises: c8370843b0b0
Create Date: 2025-03-08 21:53:49.945507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cd18eb7121b'
down_revision: Union[str, None] = 'c8370843b0b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ledger_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_values_id'), 'field_values', ['id'], unique=False)
    op.drop_constraint(None, 'fields', type_='foreignkey')
    op.create_foreign_key(None, 'fields', 'templates', ['template_id'], ['id'], ondelete='CASCADE')
    op.alter_column('ledgers', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ledgers', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_constraint(None, 'fields', type_='foreignkey')
    op.create_foreign_key(None, 'fields', 'templates', ['template_id'], ['id'])
    # 移除创建不需要的表的操作
    # op.create_table('casbin_rule',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('ptype', sa.VARCHAR(length=255), nullable=True),
    # sa.Column('v0', sa.VARCHAR(length=255), nullable=True),
    # sa.Column('v1', sa.VARCHAR(length=255), nullable=True),
    # sa.Column('v2', sa.VARCHAR(length=255), nullable=True),
    # sa.Column('v3', sa.VARCHAR(length=255), nullable=True),
    # sa.Column('v4', sa.VARCHAR(length=255), nullable=True),
    # sa.Column('v5', sa.VARCHAR(length=255), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    op.drop_index(op.f('ix_field_values_id'), table_name='field_values')
    op.drop_table('field_values')
    # ### end Alembic commands ###
