"""Add default fields to template model

Revision ID: 6c6f2e7a1122
Revises: 5bd885d93617
Create Date: 2025-03-09 22:48:49.819824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c6f2e7a1122'
down_revision: Union[str, None] = '5bd885d93617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite不支持ALTER COLUMN和外键约束，移除这些语句
    # op.drop_table('casbin_rule')
    # op.alter_column('ledgers', 'approval_status',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # op.create_foreign_key(None, 'ledgers', 'users', ['current_approver_id'], ['id'])
    # op.create_foreign_key(None, 'ledgers', 'workflows', ['workflow_id'], ['id'])
    op.add_column('templates', sa.Column('default_ledger_name', sa.String(), nullable=True))
    op.add_column('templates', sa.Column('default_description', sa.Text(), nullable=True))
    op.add_column('templates', sa.Column('default_status', sa.String(), nullable=True))
    op.add_column('templates', sa.Column('default_team_id', sa.Integer(), nullable=True))
    op.add_column('templates', sa.Column('default_metadata', sa.JSON(), nullable=True))
    # op.create_foreign_key(None, 'templates', 'teams', ['default_team_id'], ['id'])
    # op.drop_constraint(None, 'workflow_instances', type_='foreignkey')
    # op.alter_column('workflows', 'created_by',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite不支持ALTER COLUMN和外键约束，移除这些语句
    # op.alter_column('workflows', 'created_by',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    # op.create_foreign_key(None, 'workflow_instances', 'workflow_instance_nodes', ['current_node_id'], ['id'])
    # op.drop_constraint(None, 'templates', type_='foreignkey')
    op.drop_column('templates', 'default_metadata')
    op.drop_column('templates', 'default_team_id')
    op.drop_column('templates', 'default_status')
    op.drop_column('templates', 'default_description')
    op.drop_column('templates', 'default_ledger_name')
    # op.drop_constraint(None, 'ledgers', type_='foreignkey')
    # op.drop_constraint(None, 'ledgers', type_='foreignkey')
    # op.alter_column('ledgers', 'approval_status',
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    # op.create_table('casbin_rule',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('ptype', sa.VARCHAR(length=255), nullable=True),
    # sa.Column('v0', sa.VARCHAR(length=255), nullable=True),
    # sa.Column('v1', sa.VARCHAR(length=255), nullable=True),
    # sa.Column('v2', sa.VARCHAR(length=255), nullable=True),
    # sa.Column('v3', sa.VARCHAR(length=255), nullable=True),
    # sa.Column('v4', sa.VARCHAR(length=255), nullable=True),
    # sa.Column('v5', sa.VARCHAR(length=255), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###
