"""Add last_password_change to User model

Revision ID: c8370843b0b0
Revises: 
Create Date: 2025-03-08 21:24:17.331537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8370843b0b0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 移除删除不存在表的操作
    # op.drop_table('casbin_rule')
    op.add_column('users', sa.Column('last_password_change', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_password_change')
    # 移除创建不需要的表的操作
    # op.create_table('casbin_rule',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('ptype', sa.VARCHAR(length=255), nullable=True),
    # sa.Column('v0', sa.VARCHAR(length=255), nullable=True),
    # sa.Column('v1', sa.VARCHAR(length=255), nullable=True),
    # sa.Column('v2', sa.VARCHAR(length=255), nullable=True),
    # sa.Column('v3', sa.VARCHAR(length=255), nullable=True),
    # sa.Column('v4', sa.VARCHAR(length=255), nullable=True),
    # sa.Column('v5', sa.VARCHAR(length=255), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###
