"""
portrait schema 集中导出

集成指南 §3 阶段 4: portrait P4 后端 API MVP
"""
from app.portrait.schemas.common import ErrorResponse, PaginatedResponse
from app.portrait.schemas.profile import (
    AchievementInfo,
    AchievementInfoCreate,
    AchievementInfoUpdate,
    ContactInfo,
    ContactInfoCreate,
    ContactInfoUpdate,
    EducationInfo,
    EducationInfoCreate,
    EducationInfoUpdate,
    FamilyInfo,
    FamilyInfoCreate,
    FamilyInfoUpdate,
    LanguageInfo,
    LanguageInfoCreate,
    LanguageInfoUpdate,
    PoliticalInfo,
    PoliticalInfoCreate,
    PoliticalInfoUpdate,
    Profile,
    ProfileCreate,
    ProfileFull,
    ProfileListQuery,
    ProfileUpdate,
    QualificationInfo,
    QualificationInfoCreate,
    QualificationInfoUpdate,
    ResumeInfo,
    ResumeInfoCreate,
    ResumeInfoUpdate,
    RewardInfo,
    RewardInfoCreate,
    RewardInfoUpdate,
)
from app.portrait.schemas.submission import (
    ApprovalActionRequest,
    ApprovalActionResponse,
    ApprovalRecord,
    ApprovalRecordCreate,
    MySubmissionsQuery,
    Submission,
    SubmissionCreate,
    SubmissionDetail,
    SubmissionUpdate,
)
from app.portrait.schemas.home_visit import (
    HomeVisit,
    HomeVisitApproveRequest,
    HomeVisitCreate,
    HomeVisitListItem,
    HomeVisitListResponse,
    HomeVisitRejectRequest,
    HomeVisitSubmitRequest,
    HomeVisitUpdate,
)
from app.portrait.schemas.training import (
    TrainingImportRow,
    TrainingImportSummary,
    TrainingRecord,
    TrainingRecordCreate,
    TrainingRecordUpdate,
)
from app.portrait.schemas.entry_exit import (
    EntryExitCreate,
    EntryExitImportRow,
    EntryExitImportSummary,
    EntryExitListResponse,
    EntryExitRecord,
    EntryExitStatistics,
    EntryExitUpdate,
)
from app.portrait.schemas.drill import (
    DrillCreate,
    DrillDetail,
    DrillImportRow,
    DrillImportSummary,
    DrillMatrix,
    DrillRecord,
    DrillUpdate,
)


__all__ = [
    # common
    "PaginatedResponse",
    "ErrorResponse",
    # profile
    "Profile",
    "ProfileCreate",
    "ProfileUpdate",
    "ProfileFull",
    "ProfileListQuery",
    "PoliticalInfo",
    "PoliticalInfoCreate",
    "PoliticalInfoUpdate",
    "EducationInfo",
    "EducationInfoCreate",
    "EducationInfoUpdate",
    "FamilyInfo",
    "FamilyInfoCreate",
    "FamilyInfoUpdate",
    "ResumeInfo",
    "ResumeInfoCreate",
    "ResumeInfoUpdate",
    "RewardInfo",
    "RewardInfoCreate",
    "RewardInfoUpdate",
    "QualificationInfo",
    "QualificationInfoCreate",
    "QualificationInfoUpdate",
    "AchievementInfo",
    "AchievementInfoCreate",
    "AchievementInfoUpdate",
    "LanguageInfo",
    "LanguageInfoCreate",
    "LanguageInfoUpdate",
    "ContactInfo",
    "ContactInfoCreate",
    "ContactInfoUpdate",
    # submission
    "Submission",
    "SubmissionCreate",
    "SubmissionUpdate",
    "SubmissionDetail",
    "ApprovalRecord",
    "ApprovalRecordCreate",
    "ApprovalActionRequest",
    "ApprovalActionResponse",
    "MySubmissionsQuery",
    # home_visit (P6)
    "HomeVisit",
    "HomeVisitCreate",
    "HomeVisitUpdate",
    "HomeVisitSubmitRequest",
    "HomeVisitApproveRequest",
    "HomeVisitRejectRequest",
    "HomeVisitListItem",
    "HomeVisitListResponse",
    # training (PRD §10.3 占位)
    "TrainingRecord",
    "TrainingRecordCreate",
    "TrainingRecordUpdate",
    "TrainingImportRow",
    "TrainingImportSummary",
    # entry_exit (PRD §10.1 F5-F9)
    "EntryExitRecord",
    "EntryExitCreate",
    "EntryExitUpdate",
    "EntryExitListResponse",
    "EntryExitStatistics",
    "EntryExitImportRow",
    "EntryExitImportSummary",
    # drill (PRD §10.2 F2-F4)
    "DrillRecord",
    "DrillCreate",
    "DrillUpdate",
    "DrillDetail",
    "DrillMatrix",
    "DrillImportRow",
    "DrillImportSummary",
]